name = "oauth"
main = "src/worker.ts"
compatibility_date = "2024-08-27"
workers_dev = true
nodejs_compat = true
kv_namespaces = [
    { binding = "YELBOLT_KV", id = "d9af118fa8fb4016b7d59811f3568d36" }
]
